--- #YAML:1.0
name:               XML-TreePuller
version:            0.1.3_01
abstract:           Pull interface to work with XML document fragments
author:
    - Tyler Riddle <triddle@gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Scalar::Util:       1.23
    Test::More:         0
    Tree::XPathEngine:  0.05
    XML::CompactTree:   0.03
    XML::LibXML:        1.7
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
